### ISSUE TITLE
FamixJava does not appear in BaselineOfCarrefour ???

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Carrefour#6]
in `defineDependencies` only FASTJava is declared, not FamixJava ???

**Comment by badetitou** [comment]
Carrefour is made to load on default Moose Image. 
Moose today has FamixJava included. We will add the dependency when Moose will not include FamixJava (but it often creates over maintenance nobody here want to do for carrefour) - at least, I won't do it. So maybe in the future with pleasure :)
